services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tripsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: tripsdb
    ports:
      - "27017:27017"

  zookeeper:
    image: zookeeper:3.8.1
    restart: always
    environment:
      ZOO_PERM_READ_ONLY: "no"
      ZOO_TICK_TIME: 2000
      ZOO_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6.1
    restart: always
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    ports:
      - "9092:9092"
